# Generated by Django 4.2.6 on 2023-12-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pic',
            new_name='pics',
        ),
    ]
